baseURL = 'https://twitpranikah.github.io/pranikah-web/'
languageCode = 'id-id'
title = 'Pranikah.org'
theme = 'hugo-book'

# Penting agar GitHub Pages bisa baca folder dengan benar
relativeURLs = true
canonifyURLs = true

[params]
  # Menampilkan semua folder di sidebar
  BookSection = '*'
  # Menambah fitur pencarian di web
  BookSearch = true
