baseURL = 'https://twitpranikah.github.io/pranikah-web/'
languageCode = 'id-id'
title = 'Pranikah.org'
theme = 'hugo-book'

[params]
BookLogo = 'LogoPranikah.png'
title = 'Pranikah.org'
BookSection = '*'
BookSearch = true
